name: Build App

on: [push]

jobs:
  build:

    runs-on: windows-2019  #windows-latest minimum framework 4.6.2

    steps:
    - uses: actions/checkout@v3
      name: Checkout codebase
    - uses: microsoft/setup-msbuild@v1.1
      name: Setup MSBuild
    - uses: NuGet/setup-nuget@v1.0.7
      name: Setup NuGet

    - name: Restore Nuget
      run: nuget restore RetailAppWPF.sln
    - name: Build
      run: msbuild RetailAppWPF.sln /p:Configuration=Release