name: Build App

on: [push]

jobs:
  build:
    runs-on: windows-2019  #windows-latest minimum framework 4.6.2

    steps:
    - uses: actions/checkout@v3
      name: Checkout codebase
    - uses: microsoft/setup-msbuild@v1.1
      name: Setup MSBuild
    - uses: NuGet/setup-nuget@v1.0.7
      name: Setup NuGet
    - name: Retrieve Private DLLs from S3
      run: |
        aws s3 cp ${{ secrets.S3_BUCKET }}/8.5.1/DYMO.DLS.Runtime.dll ./dymo-references/DYMO.DLS.Runtime.dll
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
        AWS_DEFAULT_REGION: 'us-west-2'  
    - run: ls ./dymo-references
    - name: Restore Nuget
      run: nuget restore RetailAppWPF.sln
    
    - name: Build
      run: msbuild RetailAppWPF.sln /p:Configuration=Release