name: Build App

on: [push]

jobs:
  build:

    runs-on: windows-2019  #windows-latest minimum framework 4.6.2

    steps:
    - uses: actions/checkout@v3
      name: Checkout codebase
    - uses: microsoft/setup-msbuild@v1.1
      name: Setup MSBuild
    - uses: NuGet/setup-nuget@v1.0.7
      name: Setup NuGet

    - name: Restore Nuget
      run: nuget restore RetailAppWPF.sln
    - name: Retrieve private DLLs
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        aws_access_key_id: ${{ secrets.S3_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.S3_SECRET }}
        source: '${{ secrets.S3_BUCKET }}/8.5.1/DYMO.DLS.Runtime.dll'
        destination: './dymo-references'
        aws_region: us-west-2
    - name: Build
      run: msbuild RetailAppWPF.sln /p:Configuration=Release